ALTER TABLE public.confirmations
  ADD COLUMN IF NOT EXISTS founding_year INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS board_affiliation TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS total_student_strength INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS accreditations TEXT,
  ADD COLUMN IF NOT EXISTS standout_milestone TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS vision TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS mission TEXT NOT NULL DEFAULT '';

ALTER TABLE public.confirmations
  ALTER COLUMN founding_year DROP DEFAULT,
  ALTER COLUMN board_affiliation DROP DEFAULT,
  ALTER COLUMN total_student_strength DROP DEFAULT,
  ALTER COLUMN standout_milestone DROP DEFAULT,
  ALTER COLUMN vision DROP DEFAULT,
  ALTER COLUMN mission DROP DEFAULT;
